name: myscheduler
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  introduction_screen: ^1.0.7
  font_awesome_flutter: ^8.8.1
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  intl_phone_number_input: ^0.2.0
  cloud_firestore: ^0.13.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets: 
    - assets/
  

